### ISSUE TITLE
Adapt Slice Factory

### ISSUE THREAD

**Issue by julianev** [TU-Berlin-DIMA/scotty-window-processor#24]
The current implementation of the Slice Factory does not reflect the decision tree for storing individual tuples in the General Stream Slicing paper.

https://github.com/TU-Berlin-DIMA/scotty-window-processor/blob/22ab2c7cc2e97dc3494d51f77762f18c32bc434d/slicing/src/main/java/de/tub/dima/scotty/slicing/slice/SliceFactory.java#L17-L22

**Comment by powibol** [comment]
Thank you very much for this pointer!
Indeed, the current implementation does not always lead to the right choice of eager and lazy slices. Thus, I added the bug label to this issue.
I believe that this issue is easy to fix since one just has to refine the if-statement to reflect the decision tree presented in Figure 4 of the [General Stream Slicing paper from EDBT 2019](https://openproceedings.org/2019/conf/edbt/EDBT19_paper_171.pdf).
